import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/WiWOSDXFT5HKi6NJNKy3AU/Material-UI-for-Figma-(and-MUI-X)-(Community)?node-id=6594%3A974380",
  {
    props: {
      label: figma.string("Label"),
      // startIcon: figma.instance("↳ Start Icon"),
      // endIcon: figma.instance("↳ End Icon"),
      endIcon: figma.boolean("End Icon"),
      startIcon: figma.boolean("Start Icon"),
      size: figma.enum("Size", {
        Large: "large",
        Medium: "medium",
        Small: "small",
      }),
      color: figma.enum("Color", {
        Primary: "primary",
        Secondary: "secondary",
        Error: "error",
        Warning: "warning",
        Info: "info",
        Success: "success",
        Inherit: "inherit",
        "Inherit (white)": "inherit--white-",
      }),
      state: figma.enum("State", {
        Enabled: "enabled",
        Hovered: "hovered",
        Focused: "focused",
        Pressed: "pressed",
        Disabled: "disabled",
      }),
      variant: figma.enum("Variant", {
        Contained: "contained",
        Outlined: "outlined",
        Text: "text",
      }),
    },
    example: (props) => <Button label={props.label}/>,
  },
)
